- name: Installing Nomad
  hosts: nomad_instances
  become: yes
  become_user: root
  roles:
    - { role: brianshumate.nomad }

  tasks:
    - name: Start nomad
      service: name=nomad state=started enabled=yes

- name: Assemble Consul cluster
  hosts: consul_instances
  any_errors_fatal: true
  become: yes
  become_user: root
  roles:
    - { role: brianshumate.consul }
